const sleepData = [
  {
    id: 1,
    date: '2026-03-14',
    bedtime: '23:18',
    wakeTime: '07:00',
    durationHours: 7.7,
    timeInBedHours: 7.97,
    sleepScore: 84,
    awakenings: 2,
    efficiency: 91,
    deepSleepHours: 1.8,
    remHours: 1.6,
    lightSleepHours: 3.9,
    awakeHours: 0.4,
    fallAsleepMinutes: 18,
    mood: 'Refreshed',
    energy: 8,
    stress: 3,
    focus: 7,
    note: 'Fell asleep faster than usual after evening stretching. Woke up feeling clear-headed and rested.',
    tags: ['Stretching', 'No caffeine late', 'Screen-free before bed'],
    timeline: [
      { width: '10%', type: 'Light', color: '#6D75B0' },
      { width: '15%', type: 'Deep', color: '#99A3FB' },
      { width: '8%', type: 'REM', color: '#FFE7BF' },
      { width: '4%', type: 'Awake', color: '#C5C6D0' },
      { width: '18%', type: 'Light', color: '#6D75B0' },
      { width: '14%', type: 'Deep', color: '#99A3FB' },
      { width: '12%', type: 'REM', color: '#FFE7BF' },
      { width: '19%', type: 'Light', color: '#6D75B0' }
    ]
  },
  {
    id: 2,
    date: '2026-03-13',
    bedtime: '22:54',
    wakeTime: '06:48',
    durationHours: 7.9,
    timeInBedHours: 8.1,
    sleepScore: 86,
    awakenings: 1,
    efficiency: 93,
    deepSleepHours: 1.9,
    remHours: 1.7,
    lightSleepHours: 3.9,
    awakeHours: 0.2,
    fallAsleepMinutes: 12,
    mood: 'Good',
    energy: 8,
    stress: 2,
    focus: 8,
    note: 'Good overall rest with a steady bedtime and no late-night interruption.',
    tags: ['Early bedtime', 'Hydrated'],
    timeline: [
      { width: '12%', type: 'Light', color: '#6D75B0' },
      { width: '16%', type: 'Deep', color: '#99A3FB' },
      { width: '10%', type: 'REM', color: '#FFE7BF' },
      { width: '3%', type: 'Awake', color: '#C5C6D0' },
      { width: '20%', type: 'Light', color: '#6D75B0' },
      { width: '14%', type: 'Deep', color: '#99A3FB' },
      { width: '11%', type: 'REM', color: '#FFE7BF' },
      { width: '14%', type: 'Light', color: '#6D75B0' }
    ]
  },
  {
    id: 3,
    date: '2026-03-12',
    bedtime: '23:31',
    wakeTime: '06:44',
    durationHours: 7.2,
    timeInBedHours: 7.45,
    sleepScore: 80,
    awakenings: 2,
    efficiency: 89,
    deepSleepHours: 1.5,
    remHours: 1.5,
    lightSleepHours: 3.8,
    awakeHours: 0.4,
    fallAsleepMinutes: 15,
    mood: 'Okay',
    energy: 7,
    stress: 4,
    focus: 6,
    note: 'Slightly later night than normal, but still a decent rest.',
    tags: ['Late study session'],
    timeline: [
      { width: '14%', type: 'Light', color: '#6D75B0' },
      { width: '14%', type: 'Deep', color: '#99A3FB' },
      { width: '9%', type: 'REM', color: '#FFE7BF' },
      { width: '5%', type: 'Awake', color: '#C5C6D0' },
      { width: '22%', type: 'Light', color: '#6D75B0' },
      { width: '12%', type: 'Deep', color: '#99A3FB' },
      { width: '10%', type: 'REM', color: '#FFE7BF' },
      { width: '14%', type: 'Light', color: '#6D75B0' }
    ]
  },
  {
    id: 4,
    date: '2026-03-11',
    bedtime: '23:07',
    wakeTime: '07:14',
    durationHours: 8.1,
    timeInBedHours: 8.28,
    sleepScore: 89,
    awakenings: 1,
    efficiency: 94,
    deepSleepHours: 2.0,
    remHours: 1.7,
    lightSleepHours: 4.1,
    awakeHours: 0.18,
    fallAsleepMinutes: 10,
    mood: 'Great',
    energy: 9,
    stress: 2,
    focus: 8,
    note: 'One of the best nights this week with strong deep sleep and minimal interruption.',
    tags: ['Walked in evening', 'No screens'],
    timeline: [
      { width: '10%', type: 'Light', color: '#6D75B0' },
      { width: '17%', type: 'Deep', color: '#99A3FB' },
      { width: '10%', type: 'REM', color: '#FFE7BF' },
      { width: '2%', type: 'Awake', color: '#C5C6D0' },
      { width: '18%', type: 'Light', color: '#6D75B0' },
      { width: '15%', type: 'Deep', color: '#99A3FB' },
      { width: '12%', type: 'REM', color: '#FFE7BF' },
      { width: '16%', type: 'Light', color: '#6D75B0' }
    ]
  }
]

export default sleepData
